FROM python:3.12

COPY . /
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN pyinstaller --onefile --name VentiDemo VentiDemo.py
RUN mv dist/* ..
EXPOSE 9750
CMD ["../VentiDemo"]